### ISSUE TITLE
GEOS needed?

### ISSUE THREAD

**Issue by arnaudlimbourg** [fcurella/django-fakery#5]
Hello,

I had to install geos to be able to run any code. I don't use any geospatial code so it requiring geos does not make sense.

Is that intentional?

Thanks!

**Comment by fcurella** [comment]
Hi @arnaudlimbourg ,

No, geos is supposed to be optional.

Thanks for the report, I'll look into it.

**Comment by arnaudlimbourg** [comment]
I see https://github.com/fcurella/django-fakery/blob/master/django_fakery/fakes.py#L3 which may be a cause.

I'm having trouble using the package overall. It doesn't seem to want to save any other parameter on a user than the username.

e.g:

```python
factory.make(
    'users.User',
    fields={
        'username': lambda n,f:f.user_name(),'city':lambda n,f:f.city()
    }
)
```

It does create a user but it has no city, just a blank string :(

I must be doing something wrong but I can't figure out.

**Comment by fcurella** [comment]
Hi @arnaudlimbourg ,

Could you open a different issue for the blank city? That will help me keeping things straights.

Thank you very much for your help, I appreciate :)

**Comment by fcurella** [comment]
@arnaudlimbourg 
> It does create a user but it has no city, just a blank string :(

Fixing this in #8
