### ISSUE TITLE
Reference instance fields inside `lambda`

### ISSUE THREAD

**Issue by sobolevn** [fcurella/django-fakery#54]
Hi! Thanks a lot for building this project.

I try to solve this problem:

```python
fakery.m(User)(
    username='test',
    email=lambda n, f, instance: '{0}@example.com'.format(instance.username)
)
```

But I am not sure that I am able to with `django-fakery` currently.

**Comment by fcurella** [comment]
You can use the [`pre_save` hook](https://django-fakery.readthedocs.io/en/stable/hooks.html) to call any logic you want right before the changes are committed to the database. This includes setting fields on the instance:

```python
fakery.m(
    User,
    pre_save=[
        lambda i: i.email = '{0}@example.com'.format(i.username)
    ],
)(username='test')
```

**Comment by sobolevn** [comment]
Awesome! Thanks.
