### ISSUE TITLE
Using outdated and insecure faker

### ISSUE THREAD

**Issue by sobolevn** [fcurella/django-fakery#58]
Currently `django-fakery` uses `Faker = ">=2.0,<2.1"`
It is reported as insecure by `safety`: 

```
» safety check --bare --full-report
faker
```

**Comment by sobolevn** [comment]
Ok, here's the failing build: https://travis-ci.org/github/fcurella/django-fakery/jobs/669775616

Python 2 is the reason. I can drop it?

**Comment by fcurella** [comment]
> Python 2 is the reason. Сan I drop it?

Yes, feel free to remove it :)

Thank you so much for your work!
